# Generated by Django 5.2.8 on 2025-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='annual_quota',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
