# Generated by Django 5.2.8 on 2025-12-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employeecontract_salaryraiserequest_workreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days_per_week', models.CharField(default='sun,mon,tue,wed,thu', max_length=50)),
                ('official_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('leave_types', models.JSONField(default=list, help_text='مثال: [{"code":"annual","label":"سنوية","color":"#22c55e","days":21}]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('default_days_per_year', models.PositiveSmallIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
    ]
