# Generated by Django 5.2.8 on 2025-12-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('leave_status', 'Leave Status'), ('raise_status', 'Raise Status'), ('payroll_new', 'New Payroll'), ('visa_expiry', 'Visa / Residence Expiry'), ('document_expiry', 'Document Expiry'), ('contract_expiry', 'Contract / Insurance Expiry'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
