# Generated by Django 5.2.8 on 2025-12-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('hr', 'HR'), ('payroll', 'Payroll'), ('leave', 'Leave'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
