# Generated by Django 5.2.8 on 2025-12-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_notification_options_notification_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaresidence',
            name='is_passport_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visaresidence',
            name='is_residence_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'جواز'), ('residence', 'إقامة'), ('contract', 'عقد'), ('certificate', 'شهادة'), ('insurance', 'تأمين'), ('other', 'أخرى')], max_length=50),
        ),
    ]
