# Generated by Django 5.2.8 on 2025-11-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivitylog',
            name='event_type',
            field=models.CharField(default='order_status_change', max_length=50),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
