# Generated by Django 5.2.8 on 2025-11-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderactivitylog_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderactivitylog',
            name='event_type',
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
