# Generated by Django 5.2.8 on 2025-11-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderactivitylog_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivitylog',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.order'),
        ),
    ]
