# Generated by Django 5.2.8 on 2025-11-29 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderactivitylog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactivitylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='orders.order'),
        ),
    ]
