# Generated by Django 5.2.8 on 2025-12-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productaddon"),
        ("orders", "0010_table_order_discount_amount_order_discount_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemAddon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("price_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("addon", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="products.productaddon")),
                ("order_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addons", to="orders.orderitem")),
            ],
        ),
    ]
