# Generated by Django 5.2.8 on 2025-12-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='CafeMS Demo', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('primary_color', models.CharField(default='#f59e0b', max_length=20)),
                ('secondary_color', models.CharField(default='#4c1d95', max_length=20)),
                ('accent_color', models.CharField(default='#0f172a', max_length=20)),
                ('background_color', models.CharField(default='#f8fafc', max_length=20)),
                ('text_color', models.CharField(default='#111827', max_length=20)),
                ('header_title', models.CharField(blank=True, default='', max_length=255)),
                ('header_subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notification_email', models.EmailField(blank=True, default='', help_text='العنوان الرئيسي الذي تُرسل منه التنبيهات والتحقق.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='store/favicon/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='store/hero/')),
                ('header_links', models.JSONField(blank=True, default=list)),
                ('footer_links', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
