# Generated by Django 5.2.8 on 2025-12-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='hero_button_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
