# Generated by Django 5.2.8 on 2025-12-04 01:40

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings_hero_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='hero_cards',
            field=models.JSONField(blank=True, default=apps.store.models.default_hero_cards),
        ),
    ]
