# Generated by Django 5.2.8 on 2025-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storesettings_about_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/about/'),
        ),
    ]
