# Generated by Django 5.2.8 on 2025-12-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_storesettings_support_reply_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='wallet_pass_base_url',
            field=models.URLField(blank=True, default='', help_text='الدومين الأساسي المستخدم في روابط بطاقات الولاء (Apple/Google Wallet).'),
        ),
    ]
