# Generated by Django 5.2.8 on 2025-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
