# Generated by Django 5.2.8 on 2025-11-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='can_manage_support_chat',
            new_name='can_manage_contact_messages',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='can_view_contact_messages',
            new_name='can_manage_support',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
