# Generated by Django 5.2.8 on 2025-11-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rolepermission_can_view_user_activity_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='role',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
