# Generated by Django 5.2.8 on 2025-11-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_useractivity_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
