# Generated by Django 5.2.8 on 2025-11-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useractivity_action_alter_useractivity_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hr_role',
            field=models.CharField(choices=[('none', 'None'), ('staff', 'HR Staff'), ('supervisor', 'HR Supervisor'), ('manager', 'HR Manager')], default='none', max_length=20),
        ),
    ]
