# Generated by Django 5.2.8 on 2025-12-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_hr_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_hr_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_hr_leaves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_hr_payroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_hr_work_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_hr_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
