# Generated by Django 5.2.8 on 2025-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rolepermission_can_manage_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_hr_repoerts',
            field=models.BooleanField(default=False),
        ),
    ]
