# Generated by Django 5.2.8 on 2025-12-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rolepermission_can_manage_hr_repoerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_store_settings',
            field=models.BooleanField(default=False),
        ),
    ]
