# Generated by Django 5.2.8 on 2025-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rolepermission_can_manage_store_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_access_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_tables',
            field=models.BooleanField(default=False),
        ),
    ]
