# Generated by Django 5.2.8 on 2025-12-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rolepermission_can_access_cashier_and_more'),
        ('orders', '0010_table_order_discount_amount_order_discount_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermission',
            old_name='can_manage_hr_repoerts',
            new_name='can_manage_hr_reports',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_subcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_hr_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activity_entries', to='orders.order'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='order_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='table_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
