# Generated by Django 5.2.8 on 2025-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_can_manage_hr_repoerts_rolepermission_can_manage_hr_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_loyalty',
            field=models.BooleanField(default=False),
        ),
    ]
