# Generated by Django 5.2.8 on 2026-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_is_phone_verified_user_phone_otp_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_financial_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_suppliers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_accounting',
            field=models.BooleanField(default=False),
        ),
    ]
