# Generated by Django 5.2.8 on 2025-12-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_table_order_discount_amount_order_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('earn_rate', models.DecimalField(decimal_places=2, default=1, help_text='عدد النقاط لكل 1 ريال يتم إنفاقه.', max_digits=6)),
                ('auto_reward_threshold', models.PositiveIntegerField(default=100, help_text='الحد الأدنى للنقاط قبل منح مكافأة تلقائية.')),
                ('auto_reward_message', models.CharField(blank=True, default='مبروك! تم منحك مكافأة الولاء.', max_length=255)),
                ('reward_discount_percent', models.DecimalField(decimal_places=2, default=5, help_text='نسبة الخصم التلقائي عند بلوغ الحد.', max_digits=5)),
                ('qr_prefix', models.CharField(default='CAFLOY', help_text='بادئة QR/ID لجميع الأعضاء.', max_length=20)),
                ('pass_primary_color', models.CharField(default='#f59e0b', max_length=7)),
                ('pass_secondary_color', models.CharField(default='#4c1d95', max_length=7)),
                ('pass_label_color', models.CharField(default='#ffffff', max_length=7)),
                ('pass_logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('last_reward_at', models.DateTimeField(blank=True, null=True)),
                ('apple_wallet_pass_id', models.CharField(blank=True, default='', max_length=120)),
                ('google_wallet_pass_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('order', 'Order'), ('reward', 'Reward'), ('manual', 'Manual'), ('scan', 'QR Scan')], default='order', max_length=20)),
                ('points_delta', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
