# Generated by Django 5.2.8 on 2026-01-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_loyaltyprofile_apple_wallet_auth_token_and_registration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loyaltypassregistration',
            new_name='loyalty_loy_device__1c9d46_idx',
            old_name='loyalty_loy_device__b8c4c4_idx',
        ),
    ]
