# Generated by Django 5.2.8 on 2026-01-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_rename_loyalty_loy_device__b8c4c4_idx_loyalty_loy_device__1c9d46_idx'),
        ('loyalty', '0004_update_loyalty_pass_colors'),
    ]

    operations = [
    ]
