# Generated by Django 5.2.8 on 2026-01-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_merge_20260107_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltysettings',
            name='pass_label_color',
            field=models.CharField(default='#f59e0b', max_length=7),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='pass_primary_color',
            field=models.CharField(default='#0b0f19', max_length=7),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='pass_secondary_color',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
    ]
