# Generated by Django 5.2.8 on 2025-11-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_delivery_fee_order_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('cash', 'Cash / نقدًا'), ('card', 'Card (Visa/Master/Mada)'), ('tabby', 'Tabby'), ('tamara', 'Tamara'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('mada', 'Mada')], help_text='كود ثابت يُستخدم في التكامل مع بوابات الدفع (تابي/تمارا/مدى...).', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='هل تظهر طريقة الدفع هذه للعملاء؟')),
                ('is_online', models.BooleanField(default=False, help_text='طرق الدفع التي تحتاج تكامل API (تابي/تمارا/Apple Pay/Google Pay...).')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='لترتيب طرق الدفع في واجهة المستخدم.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, help_text='رقم العملية في بوابة الدفع (تابي/تمارا/مدى/ApplePay...).', max_length=255)),
                ('provider_raw_response', models.JSONField(blank=True, help_text='الاستجابة الخام من بوابة الدفع للاطلاع فقط.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentmethod')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
