# Generated by Django 5.2.8 on 2025-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_guestemailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemailverification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
