# Generated by Django 5.2.8 on 2025-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_guestemailverification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('staff', 'موظف'), ('supervisor', 'مشرف'), ('manager', 'مدير'), ('bot', 'رد آلي'), ('guest', 'ضيف')], max_length=20),
        ),
    ]
