# Generated by Django 5.2.8 on 2025-11-29 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_conversation_bot_disabled_conversation_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reply', 'رد على محادثة دعم'), ('delete_conversation', 'حذف محادثة دعم')], max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=150, null=True)),
                ('target_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='support.conversation')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_activities', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
