# Generated by Django 5.2.8 on 2025-11-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_supportactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaffactivity',
            name='staff_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supportstaffactivity',
            name='staff_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SupportActivityLog',
        ),
    ]
