# Generated by Django 5.2.8 on 2025-12-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0009_supportstaffactivity_staff_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="guest_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]

