export const copy = {
  brandFallback: "CafeMS Demo",
  taglineFallback:
    "سندوتشات طازجة، خفايف شهية، وإفطار سريع بطابع خليجي. تجربة سهلة من الطلب حتى الاستلام.",
  heroFallback: [
    {
      title: "أهلاً بكم في CafeMS Demo",
      description: "ساندوتشات طازجة وخفايف مجهزة على طلبكم بخلطاتنا الخاصة ولمسة من الامتنان.",
      image: "https://images.unsplash.com/photo-1459257868276-5e65389e2722?auto=format&fit=crop&w=1200&q=80",
      button_text: "ابدأ الطلب الآن",
      button_link: "/menu?category=1",
    },
    {
      title: "خفايف تمنحك الطاقة",
      description: "برجر، فلافل، وخيارات خفيفة تجعل استراحة منتصف اليوم ألذ وأسرع.",
      image: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?auto=format&fit=crop&w=1200&q=80",
      button_text: "جرب الخفايف",
      button_link: "/menu?category=2",
    },
    {
      title: "إفطار طازج ولطيف",
      description: "مشروبات ساخنة وباردة، بيض وحلومي، وخبز محمّص يجهز حالاً لبدء يومك.",
      image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=80",
      button_text: "ابدأ فطورك",
      button_link: "/menu?category=3",
    },
  ],
  contactFallback: {
    address: "الدمام - المملكة العربية السعودية",
    hours: "يومياً من 6 صباحاً حتى 1 صباحاً",
    phone: "+10000000000",
    email: "contact@example.invalid",
    whatsapp: "+10000000000",
  },
  categoryFallbacks: [
    {
      title: "ساندوتشات",
      image: "https://res.cloudinary.com/dnsx3jzec/image/upload/v1707474032/cafems/sandwiches.jpg",
    },
    {
      title: "خفايف ومقبلات",
      image: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?auto=format&fit=crop&w=1200&q=80",
    },
    {
      title: "مشروبات وإفطار",
      image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=80",
    },
    {
      title: "حلويات وعصائر",
      image: "https://res.cloudinary.com/dnsx3jzec/image/upload/v1707474032/cafems/cold-drinks.jpg",
    },
  ],
  messages: {
    required: "هذا الحقل مطلوب، يرجى تعبئته.",
    passwordMismatch: "كلمتا المرور غير متطابقتين. يرجى التأكد والمحاولة مرة أخرى.",
    genericError: "حدث خطأ غير متوقع. حاول مجدداً أو تواصل مع الدعم.",
    loading: "جاري التحميل...",
  },
  home: {
    headerTagline:
      "CafeMS Demo محطتكم اليومية للاستمتاع بسندوتشات طازجة، خفايف شهية، ومشروبات تعكس ذائقة الخليج. تجربة سهلة من الطلب حتى الاستلام.",
    heroSecondaryCta: "تتبع الطلب",
    heroExploreCta: "ابدأ الطلب الآن",
    quickIntro: "اطلب سندوتشات، خفايف، وإفطار طازج بسرعة وسهولة.",
    infoTags: ["تحضير سريع", "مكونات طازجة", "دفع آمن"],
    quickActions: [
      {
        icon: "grid-outline",
        label: "استكشف القائمة",
        helper: "أصناف جاهزة مع صور وتفاصيل",
        route: "Menu",
      },
      {
        icon: "time-outline",
        label: "تتبع الطلب",
        helper: "اعرف حالة طلبك لحظياً",
        route: "OrderTracking",
      },
      {
        icon: "document-text-outline",
        label: "طلباتي",
        helper: "سجل الطلبات السابقة والمكررة",
        route: "Orders",
      },
      {
        icon: "book-outline",
        label: "قصتنا",
        helper: "تعرف على بدايتنا وشغفنا",
        route: "Story",
      },
      {
        icon: "gift-outline",
        label: "المكافآت",
        helper: "نقاط وعروض للعملاء الدائمين",
        route: "Rewards",
      },
      {
        icon: "call-outline",
        label: "تواصل معنا",
        helper: "نخدمك عبر الهاتف أو الواتساب",
        route: "Contact",
      },
    ],
    categoriesTitle: "الأقسام",
    categoriesCta: "عرض الكل",
    featuredTitle: "أصناف مختارة",
    featuredCta: "اذهب للقائمة كاملة",
    featuredEmpty: "لا توجد أصناف متاحة حالياً. عد لاحقاً أو تواصل معنا.",
  },
  menu: {
    title: "القائمة بطابع خليجي",
    subtitle: "تصفح الساندوتشات، الخفايف، والمشروبات. اختر القسم الذي تفضله وابدأ الطلب فوراً.",
    searchPlaceholder: "ابحث عن صنف أو مكون...",
    loading: "جاري تجهيز القائمة...",
    emptyTitle: "لا توجد أصناف لعرضها حالياً",
    emptyDescription: "جرّب تغيير الفلتر أو الرجوع لاحقاً، أو تواصل معنا للمساعدة.",
    filterAll: "كل الأقسام",
    cartCtaFilled: "اذهب للسلة",
    cartCtaEmpty: "أضف أول صنف للسلة",
    allCategories: "كل الأقسام",
  },
  orders: {
    prompt: "سجل دخولك لتتمكن من استعراض طلباتك وحفظها.",
    errorEmpty: "لا توجد طلبات مسجلة لهذا الحساب.",
    notFound: "الطلب غير متاح حالياً.",
    fetchError: "تعذر تحميل الطلبات. حاول مجدداً.",
    guestTitle: "للمتابعة تحتاج لتسجيل الدخول",
    guestDescription: "نحفظ طلباتك وربطها بحسابك لتتبعها بسهولة وتكرارها بسرعة.",
    login: "تسجيل دخول",
    register: "إنشاء حساب",
  },
  more: {
    guestWelcome: "مرحباً! ضيفنا الكريم في CafeMS Demo",
    guestBody: "سجل دخولك لتحفظ طلباتك وعناوينك وتتابع نقاط المكافآت.",
    morePagesTitle: "صفحات أخرى",
    supportTitle: "الدعم والمساعدة",
    supportDescription: "تحتاج مساعدة؟ تواصل معنا لنحل أي مشكلة في الطلب أو الحساب.",
  },
};
