# Generated by Django 5.2.8 on 2025-12-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_description_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAddon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("price_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addons", to="products.product")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
